bundler_args: --without development

before_install:
  - gem install bundler -v '> 1.5.0'

rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2

script: bundle exec rake

branches:
  only:
    - master

services:
  - mongodb
