production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] || ENV['MONGOHQ_URL'] %>
development:
  clients:
    default:
      uri: mongodb://localhost:27017/fixme
test:
  clients:
    default:
      uri: mongodb://localhost:27017/fixme
