production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOLAB_URI'] %>
      options:
        retry_writes: false
development:
  clients:
    default:
      uri: mongodb://localhost:27017/fixme
test:
  clients:
    default:
      uri: mongodb://localhost:27017/fixme
