name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby: ['2.7', '3.0']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake spec
